## ДЗ №2. Матричные факторизации

#### В этой домашке вам предстоит реализовать некоторые базовые модели матричной факторизации

#### Дата выдачи: 17.02.25

#### Мягкий дедлайн: 02.03.25 23:59 MSK

#### Жесткий дедлайн: 09.03.25 23:59 MSK

В этом задании мы будем работать с классическим для рекоендательных систем датасетом [MovieLens 1M](https://grouplens.org/datasets/movielens/1m/). Датасет содержит рейтинги оценки для 4000 фильмов от 6000 пользователей. Более подробное описание можете найти на странице с датасетом и в README файле

In [ ]:
#!wget https://files.grouplens.org/datasets/movielens/ml-1m.zip
#!unzip ml-1m.zip
#!cat ml-1m/README

In [1]:
import pandas as pd
import numpy as np
from typing import Union
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("ml-1m/ratings.dat", sep='::', names=['user_id', 'item_id', 'rating', 'timestamp'], engine='python')
df['datetime'] = pd.to_datetime(df['timestamp'], unit='s')
df.drop('timestamp', axis=1, inplace=True)
df.head()

user_id  item_id  rating            datetime
0        1     1193       5 2000-12-31 22:12:40
1        1      661       3 2000-12-31 22:35:09
2        1      914       3 2000-12-31 22:32:48
3        1     3408       4 2000-12-31 22:04:35
4        1     2355       5 2001-01-06 23:38:11

In [3]:
value_counts = df['item_id'].value_counts()
filtered_values = value_counts[value_counts > 20].index
df = df[df['item_id'].isin(filtered_values)].copy()

In [4]:
df['datetime'].min(),df['datetime'].max()

(Timestamp('2000-04-25 23:05:32'), Timestamp('2003-02-28 17:49:50'))

In [5]:
train_end = '2000-12-01'
df_train = df[df['datetime'] < train_end].copy()
df_test = df[df['datetime'] >= train_end].copy()
df_train.shape, df_test.shape

((787420, 4), (207432, 4))

In [6]:
train_users = df_train['user_id'].unique()
train_items = df_train['item_id'].unique()

df_test = df_test[df_test['user_id'].isin(train_users)]
df_test = df_test[df_test['item_id'].isin(train_items)]
df_test.shape

(106471, 4)

In [7]:
user_le = LabelEncoder()
item_le = LabelEncoder()

df_train['user_id'] = user_le.fit_transform(df_train['user_id'])
df_train['item_id'] = item_le.fit_transform(df_train['item_id'])

df_test['user_id'] = user_le.transform(df_test['user_id'])
df_test['item_id'] = item_le.transform(df_test['item_id'])

In [8]:
[df_train['user_id'].nunique(), df_train['user_id'].max(), df_train['user_id'].max(),
df_train['item_id'].nunique(), df_train['item_id'].min(), df_train['item_id'].max(),
df_train['rating'].nunique(), df_train['rating'].min(),df_train['rating'].max()]

[5365,
 np.int64(5364),
 np.int64(5364),
 3010,
 np.int64(0),
 np.int64(3009),
 5,
 np.int64(1),
 np.int64(5)]

In [9]:
df_train.shape

(787420, 4)

##### Задание 1. Напишем функцию, которая превратит датафрейм в матрицу интеракций. В функции df_to_matrix реализуйте функцию, которая принимает датафрейм и возвращает np.array матрицу интеракций. В функции df_to_coo реализуйте функцию, которая принимает датафрейм и возвращает разреженную матрицу интеракций в coo_array формате

In [10]:
def df_to_matrix(df: pd.DataFrame) -> np.ndarray:
    df_matrix = df.pivot(index='user_id', columns='item_id', values='rating')
    df_matrix = df_matrix.fillna(0)

    print(f"Размер матрицы в pd: {df_matrix.shape}")
    print(f"\n{df_matrix.head(2)}")


    result = df_matrix.to_numpy()
    
    
    print(f"\nРазмер матрицы в np:{result.shape}")
    print(f"\n{result[2:]}")

    user_ids = df_matrix.index.to_numpy()
    item_ids = df_matrix.columns.to_numpy()

    print(f"\nuser_id: {user_ids}")
    print(f"item_id: {item_ids}")
    

    return result #shape ~ [n_users, n_items]

In [11]:
interactions = df_to_matrix(df_train)

Размер матрицы в pd: (5365, 3010)

item_id  0     1     2     3     4     5     6     7     8     9     ...  \
user_id                                                              ...   
0         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
1         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   

item_id  3000  3001  3002  3003  3004  3005  3006  3007  3008  3009  
user_id                                                              
0         0.0   0.0   0.0   0.0   0.0   1.0   4.0   0.0   0.0   0.0  
1         0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[2 rows x 3010 columns]

Размер матрицы в np:(5365, 3010)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 3. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [3. 0. 0. ... 0. 0. 0.]]

user_id: [   0    1    2 ... 5362 5363 5364]
item_id: [   0    1    2 ... 3007 3008 3009]


In [12]:
from scipy.sparse import coo_array

def df_to_coo(df: pd.DataFrame) -> coo_array:

    result = coo_array((df["rating"], (df["user_id"], df["item_id"])))

    return result # coo_array

In [13]:
coo_interactions = df_to_coo(df_train)
print(coo_interactions)

<COOrdinate sparse array of dtype 'int64'
	with 787420 stored elements and shape (5365, 3010)>
  Coords	Values
  (0, 2994)	3
  (0, 929)	4
  (0, 567)	4
  (0, 3005)	1
  (0, 3006)	4
  (0, 1533)	3
  (0, 1539)	3
  (0, 1541)	2
  (0, 957)	3
  (0, 1549)	2
  (0, 2301)	5
  (0, 1554)	2
  (0, 666)	4
  (0, 672)	4
  (0, 674)	5
  (0, 681)	3
  (0, 682)	2
  (0, 685)	5
  (0, 687)	3
  (0, 691)	3
  (0, 1815)	2
  (0, 718)	3
  (0, 2355)	3
  (0, 1219)	2
  (0, 2467)	2
  :	:
  (5364, 2119)	4
  (5364, 2122)	1
  (5364, 449)	5
  (5364, 1473)	1
  (5364, 456)	4
  (5364, 1479)	5
  (5364, 1480)	4
  (5364, 2852)	4
  (5364, 1488)	5
  (5364, 462)	4
  (5364, 801)	5
  (5364, 803)	2
  (5364, 469)	4
  (5364, 1489)	3
  (5364, 1490)	3
  (5364, 1491)	5
  (5364, 1497)	5
  (5364, 804)	4
  (5364, 812)	4
  (5364, 813)	3
  (5364, 814)	1
  (5364, 817)	5
  (5364, 478)	5
  (5364, 819)	4
  (5364, 820)	4


In [14]:
assert (interactions != 0).sum() == df_train.shape[0]
assert interactions[0, 2994] == 3
assert interactions[2369, 1203] == 5
assert interactions[1557, 459] == 3
assert np.allclose(coo_interactions.toarray(), interactions)

##### Задание 2.1. Рассмотрим [SVD](https://en.wikipedia.org/wiki/Singular_value_decomposition). Возьмите готовую реализуцию алгоритма из numpy.linalg или из scipy.linalg и примените алгоритм к матрицам интеракций, полученным в первом задании. Для работы со sparse матрицей обычная реализация svd не подойдет и нужно будет воспользоваться scipy.sparse.linalg.svds. Вам нужно разложить матрицу интеракций на 3 матрицы U, S, V, а затем перемножить их и восстановить изначальную матрицу. При полном разложении исходная матрица должна восстанавливаться максимально хорошо

In [17]:
from scipy.sparse.linalg import svds

In [15]:
min(interactions.shape), min(coo_interactions.shape)

(3010, 3010)

In [19]:
U, S, V = svds(interactions, k=3009)

In [22]:
import numpy as np
S = np.diag(S)

In [ ]:
def make_svd(interractions: Union[np.ndarray, coo_array], n_singular_values: int = -1):
    # функция должна работать и для полной матрицы и для sparse матрицы(вам поможет isinstance).
    # если n_singular_values = -1, то берем все сингулярные числа для полной матрицы
    # и все кроме одного сингулярного числа для coo-матрицы(иначе scipy.sparse.linalg.svds не будет работать)

    
    #your code here
    
    return U, S, V

In [23]:
#U, S, V = make_svd(interactions)
assert np.allclose(U @ S @ V, interactions)

AssertionError: 

In [ ]:
U1, S1, V1 = make_svd(interactions, 10)
U, S, V = make_svd(coo_interactions, 10)
assert np.allclose(U1 @ S1 @ V1, U @ S @ V)

##### Задание 2.2. Теперь попробуем сделать рекомендации с помощью SVD. Мы научились восстанавливать исходную матрицу с помощью разложения, теперь же мы хотим порекомендовать пользователю айтемы, которые будут для него максимально релевантны(в восстановленной матрице у них будет самый высокий скор). Для каждого пользователя нужно будет найти индексы айтемов, которые имеют максимальный скор. При этом стоит обратить внимание, что мы не хотим рекомендовать пользователю айтемы, с которыми он уже взаимодействовал

In [ ]:
def make_svd_recommendations(interractions: Union[np.ndarray, coo_array], n_singular_values: int = -1, top_k: int = 100):
    # Возвращает матрицу вида n_users, top_k, то есть для каждого пользователя возвращаем индексы 
    # top_k самых релевантный айтемов среди тех с которыми он еще не взаимодействовал

    #your code here


    return recommendations #shape ~ [n_users, top_k]

In [ ]:
recs = make_svd_recommendations(interractions, -1, 100)
assert recs.shape == (interractions.shape[0], 100)

##### Задание 2.3. Теперь давайте посмотрим как будет зависеть качетво рекомендаций, от количества сингулярных чисел, которые мы возьмем в SVD разложении. Переберите n_singular_values из списка [1, 10, 50, 200, 1000] и посмотрите как будет изменяться метрика NDCG на тестовом датасете для таких рекомендаций и как будет меняться время вычисления. Для каждого графики зависимости метрики NDCG от n_singular_values и времени работы алгоритма от n_singular_values(Время работы будет меняться только для sparse-матрицы, стоит запускать алгоритм именно для нее)

In [ ]:
def plot_graphs(interractions: Union[np.ndarray, coo_array], top_k: int = 100):
    #your code here
    for n_singular_values in [1, 10, 50, 200, 1000]:
        #your code here


In [ ]:
plot_graphs()

##### Задание 3.1. Перейдем к [ALS](http://yifanhu.net/PUB/cf.pdf). Возьмем реализацию iALS из библиотеки [implicit](https://benfred.github.io/implicit/api/models/cpu/als.html). Обучите ALS на нашем датасете, сделайте top_k рекомендации для юзеров из тестового датасета, и сравните метрики ALS с метриками, которые получились в SVD. Попробуйте перебрать гиперпараметры и найдите оптимальное число факторов, коэффициент alpha и коэффициент регуляризации.

In [ ]:
def make_als_recommendations(
    interractions: Union[np.ndarray, coo_array], 
    top_k: int = 100, 
    n_factors: int = 100,
    alpha: float = 1.0,
    regularization: float = 0.01,
):
    #your code here


    return recommendations #shape ~ [n_users, top_k]

In [ ]:
recs = make_als_recommendations(interractions)
assert recs.shape == (interractions.shape[0], 100)

##### Задание 3.2. Сделайте объяснение рекомендаций для нескольких юзеров(als.explain). Воспользуйтесь файлом movies.dat чтобы перейти от индексов фильмов к их названием

In [ ]:
#your code here

##### Задание 4. До этого мы работали с рейтингами, но как обсуждалось на лекции, implicit ALS отлично работает и с implicit фидбэком. Давайте попробуем преобразовать наш датасет(трейн и тест) следующим образом

1. Бинаризуем все рейтинги(заменим любую интеракцию пользователя на 1)
2. Заменим на 1 только рейтинги 4 и 5, а рейтинг ниже 4 заменим на 0
3. Заменим на 1 только рейтинги 4 и 5, а рейтинг ниже 4 заменим на -1
4. Заменим на 1 только рейтинги 4 и 5, а рейтинг ниже 4 заменим на -1 и добавим сглаживание по времени. То есть чем дальше была интеракция от максимальной даты трейна, тем с меньшим весом мы будем ее учитывать(например можно интеракции за последний месяц брать в исходном виде, и с каждым месяцем в прошлое умножать их на какой-нибудь коэффициент меньший 1). Таким образом более старые интеракции пользователя будут вносить меньший вклад в его интересы
5. Придумайте свой вариант(опционально)

Для каждой полученной матрицы обучите iALS и SVD и сравните их результаты между собой(преобразовывать нужно только обучающую выборку, тестовую оставляем неизменной)

In [ ]:
#your code here

##### Задание 5. iALS на numpy/torch. Давайте реализуем алгоритм iALS на нумпае или торче. Требуется реализовать алгорит, описанный в 4 части [статьи](http://yifanhu.net/PUB/cf.pdf). Обратите внимания на все оптимизации, которые они описывают в статье, чтобы сократить лишние вычисления. Hint: метрики у вашего алгоритма должны быть сравнимы с метриками ALS из библиотеки implicit

In [ ]:
class iALS:
    def __init__(self, n_factors: int = 100, alpha: float = 1.0, reg_coef = 0.01):
        #your code here

    def fit(self, interractions: np.ndarray, n_iterations: int 10):
        #your code here

    def predict(self, top_k: int = 100):
        # возвращает top-k айтемов для каждого юзера(айтемы с которыми юзер взаимодействовал не должны попасть в рекомендации)
        #your code here

        return predicts # shape ~ [n_users, top_k]